require 'date'
require 'time'

module SpaceRubyTraderClient
  class TradeSymbol
    PRECIOUS_STONES = "PRECIOUS_STONES".freeze
    QUARTZ_SAND = "QUARTZ_SAND".freeze
    SILICON_CRYSTALS = "SILICON_CRYSTALS".freeze
    AMMONIA_ICE = "AMMONIA_ICE".freeze
    LIQUID_HYDROGEN = "LIQUID_HYDROGEN".freeze
    LIQUID_NITROGEN = "LIQUID_NITROGEN".freeze
    ICE_WATER = "ICE_WATER".freeze
    EXOTIC_MATTER = "EXOTIC_MATTER".freeze
    ADVANCED_CIRCUITRY = "ADVANCED_CIRCUITRY".freeze
    GRAVITON_EMITTERS = "GRAVITON_EMITTERS".freeze
    IRON = "IRON".freeze
    IRON_ORE = "IRON_ORE".freeze
    COPPER = "COPPER".freeze
    COPPER_ORE = "COPPER_ORE".freeze
    ALUMINUM = "ALUMINUM".freeze
    ALUMINUM_ORE = "ALUMINUM_ORE".freeze
    SILVER = "SILVER".freeze
    SILVER_ORE = "SILVER_ORE".freeze
    GOLD = "GOLD".freeze
    GOLD_ORE = "GOLD_ORE".freeze
    PLATINUM = "PLATINUM".freeze
    PLATINUM_ORE = "PLATINUM_ORE".freeze
    DIAMONDS = "DIAMONDS".freeze
    URANITE = "URANITE".freeze
    URANITE_ORE = "URANITE_ORE".freeze
    MERITIUM = "MERITIUM".freeze
    MERITIUM_ORE = "MERITIUM_ORE".freeze
    HYDROCARBON = "HYDROCARBON".freeze
    ANTIMATTER = "ANTIMATTER".freeze
    FAB_MATS = "FAB_MATS".freeze
    FERTILIZERS = "FERTILIZERS".freeze
    FABRICS = "FABRICS".freeze
    FOOD = "FOOD".freeze
    JEWELRY = "JEWELRY".freeze
    MACHINERY = "MACHINERY".freeze
    FIREARMS = "FIREARMS".freeze
    ASSAULT_RIFLES = "ASSAULT_RIFLES".freeze
    MILITARY_EQUIPMENT = "MILITARY_EQUIPMENT".freeze
    EXPLOSIVES = "EXPLOSIVES".freeze
    LAB_INSTRUMENTS = "LAB_INSTRUMENTS".freeze
    AMMUNITION = "AMMUNITION".freeze
    ELECTRONICS = "ELECTRONICS".freeze
    SHIP_PLATING = "SHIP_PLATING".freeze
    SHIP_PARTS = "SHIP_PARTS".freeze
    EQUIPMENT = "EQUIPMENT".freeze
    FUEL = "FUEL".freeze
    MEDICINE = "MEDICINE".freeze
    DRUGS = "DRUGS".freeze
    CLOTHING = "CLOTHING".freeze
    MICROPROCESSORS = "MICROPROCESSORS".freeze
    PLASTICS = "PLASTICS".freeze
    POLYNUCLEOTIDES = "POLYNUCLEOTIDES".freeze
    BIOCOMPOSITES = "BIOCOMPOSITES".freeze
    QUANTUM_STABILIZERS = "QUANTUM_STABILIZERS".freeze
    NANOBOTS = "NANOBOTS".freeze
    AI_MAINFRAMES = "AI_MAINFRAMES".freeze
    QUANTUM_DRIVES = "QUANTUM_DRIVES".freeze
    ROBOTIC_DRONES = "ROBOTIC_DRONES".freeze
    CYBER_IMPLANTS = "CYBER_IMPLANTS".freeze
    GENE_THERAPEUTICS = "GENE_THERAPEUTICS".freeze
    NEURAL_CHIPS = "NEURAL_CHIPS".freeze
    MOOD_REGULATORS = "MOOD_REGULATORS".freeze
    VIRAL_AGENTS = "VIRAL_AGENTS".freeze
    MICRO_FUSION_GENERATORS = "MICRO_FUSION_GENERATORS".freeze
    SUPERGRAINS = "SUPERGRAINS".freeze
    LASER_RIFLES = "LASER_RIFLES".freeze
    HOLOGRAPHICS = "HOLOGRAPHICS".freeze
    SHIP_SALVAGE = "SHIP_SALVAGE".freeze
    RELIC_TECH = "RELIC_TECH".freeze
    NOVEL_LIFEFORMS = "NOVEL_LIFEFORMS".freeze
    BOTANICAL_SPECIMENS = "BOTANICAL_SPECIMENS".freeze
    CULTURAL_ARTIFACTS = "CULTURAL_ARTIFACTS".freeze
    FRAME_PROBE = "FRAME_PROBE".freeze
    FRAME_DRONE = "FRAME_DRONE".freeze
    FRAME_INTERCEPTOR = "FRAME_INTERCEPTOR".freeze
    FRAME_RACER = "FRAME_RACER".freeze
    FRAME_FIGHTER = "FRAME_FIGHTER".freeze
    FRAME_FRIGATE = "FRAME_FRIGATE".freeze
    FRAME_SHUTTLE = "FRAME_SHUTTLE".freeze
    FRAME_EXPLORER = "FRAME_EXPLORER".freeze
    FRAME_MINER = "FRAME_MINER".freeze
    FRAME_LIGHT_FREIGHTER = "FRAME_LIGHT_FREIGHTER".freeze
    FRAME_HEAVY_FREIGHTER = "FRAME_HEAVY_FREIGHTER".freeze
    FRAME_TRANSPORT = "FRAME_TRANSPORT".freeze
    FRAME_DESTROYER = "FRAME_DESTROYER".freeze
    FRAME_CRUISER = "FRAME_CRUISER".freeze
    FRAME_CARRIER = "FRAME_CARRIER".freeze
    REACTOR_SOLAR_I = "REACTOR_SOLAR_I".freeze
    REACTOR_FUSION_I = "REACTOR_FUSION_I".freeze
    REACTOR_FISSION_I = "REACTOR_FISSION_I".freeze
    REACTOR_CHEMICAL_I = "REACTOR_CHEMICAL_I".freeze
    REACTOR_ANTIMATTER_I = "REACTOR_ANTIMATTER_I".freeze
    ENGINE_IMPULSE_DRIVE_I = "ENGINE_IMPULSE_DRIVE_I".freeze
    ENGINE_ION_DRIVE_I = "ENGINE_ION_DRIVE_I".freeze
    ENGINE_ION_DRIVE_II = "ENGINE_ION_DRIVE_II".freeze
    ENGINE_HYPER_DRIVE_I = "ENGINE_HYPER_DRIVE_I".freeze
    MODULE_MINERAL_PROCESSOR_I = "MODULE_MINERAL_PROCESSOR_I".freeze
    MODULE_GAS_PROCESSOR_I = "MODULE_GAS_PROCESSOR_I".freeze
    MODULE_CARGO_HOLD_I = "MODULE_CARGO_HOLD_I".freeze
    MODULE_CARGO_HOLD_II = "MODULE_CARGO_HOLD_II".freeze
    MODULE_CARGO_HOLD_III = "MODULE_CARGO_HOLD_III".freeze
    MODULE_CREW_QUARTERS_I = "MODULE_CREW_QUARTERS_I".freeze
    MODULE_ENVOY_QUARTERS_I = "MODULE_ENVOY_QUARTERS_I".freeze
    MODULE_PASSENGER_CABIN_I = "MODULE_PASSENGER_CABIN_I".freeze
    MODULE_MICRO_REFINERY_I = "MODULE_MICRO_REFINERY_I".freeze
    MODULE_SCIENCE_LAB_I = "MODULE_SCIENCE_LAB_I".freeze
    MODULE_JUMP_DRIVE_I = "MODULE_JUMP_DRIVE_I".freeze
    MODULE_JUMP_DRIVE_II = "MODULE_JUMP_DRIVE_II".freeze
    MODULE_JUMP_DRIVE_III = "MODULE_JUMP_DRIVE_III".freeze
    MODULE_WARP_DRIVE_I = "MODULE_WARP_DRIVE_I".freeze
    MODULE_WARP_DRIVE_II = "MODULE_WARP_DRIVE_II".freeze
    MODULE_WARP_DRIVE_III = "MODULE_WARP_DRIVE_III".freeze
    MODULE_SHIELD_GENERATOR_I = "MODULE_SHIELD_GENERATOR_I".freeze
    MODULE_SHIELD_GENERATOR_II = "MODULE_SHIELD_GENERATOR_II".freeze
    MODULE_ORE_REFINERY_I = "MODULE_ORE_REFINERY_I".freeze
    MODULE_FUEL_REFINERY_I = "MODULE_FUEL_REFINERY_I".freeze
    MOUNT_GAS_SIPHON_I = "MOUNT_GAS_SIPHON_I".freeze
    MOUNT_GAS_SIPHON_II = "MOUNT_GAS_SIPHON_II".freeze
    MOUNT_GAS_SIPHON_III = "MOUNT_GAS_SIPHON_III".freeze
    MOUNT_SURVEYOR_I = "MOUNT_SURVEYOR_I".freeze
    MOUNT_SURVEYOR_II = "MOUNT_SURVEYOR_II".freeze
    MOUNT_SURVEYOR_III = "MOUNT_SURVEYOR_III".freeze
    MOUNT_SENSOR_ARRAY_I = "MOUNT_SENSOR_ARRAY_I".freeze
    MOUNT_SENSOR_ARRAY_II = "MOUNT_SENSOR_ARRAY_II".freeze
    MOUNT_SENSOR_ARRAY_III = "MOUNT_SENSOR_ARRAY_III".freeze
    MOUNT_MINING_LASER_I = "MOUNT_MINING_LASER_I".freeze
    MOUNT_MINING_LASER_II = "MOUNT_MINING_LASER_II".freeze
    MOUNT_MINING_LASER_III = "MOUNT_MINING_LASER_III".freeze
    MOUNT_LASER_CANNON_I = "MOUNT_LASER_CANNON_I".freeze
    MOUNT_MISSILE_LAUNCHER_I = "MOUNT_MISSILE_LAUNCHER_I".freeze
    MOUNT_TURRET_I = "MOUNT_TURRET_I".freeze
    SHIP_PROBE = "SHIP_PROBE".freeze
    SHIP_MINING_DRONE = "SHIP_MINING_DRONE".freeze
    SHIP_SIPHON_DRONE = "SHIP_SIPHON_DRONE".freeze
    SHIP_INTERCEPTOR = "SHIP_INTERCEPTOR".freeze
    SHIP_LIGHT_HAULER = "SHIP_LIGHT_HAULER".freeze
    SHIP_COMMAND_FRIGATE = "SHIP_COMMAND_FRIGATE".freeze
    SHIP_EXPLORER = "SHIP_EXPLORER".freeze
    SHIP_HEAVY_FREIGHTER = "SHIP_HEAVY_FREIGHTER".freeze
    SHIP_LIGHT_SHUTTLE = "SHIP_LIGHT_SHUTTLE".freeze
    SHIP_ORE_HOUND = "SHIP_ORE_HOUND".freeze
    SHIP_REFINING_FREIGHTER = "SHIP_REFINING_FREIGHTER".freeze
    SHIP_SURVEYOR = "SHIP_SURVEYOR".freeze

    def self.all_vars
      @all_vars ||= [PRECIOUS_STONES, QUARTZ_SAND, SILICON_CRYSTALS, AMMONIA_ICE, LIQUID_HYDROGEN, LIQUID_NITROGEN, ICE_WATER, EXOTIC_MATTER, ADVANCED_CIRCUITRY, GRAVITON_EMITTERS, IRON, IRON_ORE, COPPER, COPPER_ORE, ALUMINUM, ALUMINUM_ORE, SILVER, SILVER_ORE, GOLD, GOLD_ORE, PLATINUM, PLATINUM_ORE, DIAMONDS, URANITE, URANITE_ORE, MERITIUM, MERITIUM_ORE, HYDROCARBON, ANTIMATTER, FAB_MATS, FERTILIZERS, FABRICS, FOOD, JEWELRY, MACHINERY, FIREARMS, ASSAULT_RIFLES, MILITARY_EQUIPMENT, EXPLOSIVES, LAB_INSTRUMENTS, AMMUNITION, ELECTRONICS, SHIP_PLATING, SHIP_PARTS, EQUIPMENT, FUEL, MEDICINE, DRUGS, CLOTHING, MICROPROCESSORS, PLASTICS, POLYNUCLEOTIDES, BIOCOMPOSITES, QUANTUM_STABILIZERS, NANOBOTS, AI_MAINFRAMES, QUANTUM_DRIVES, ROBOTIC_DRONES, CYBER_IMPLANTS, GENE_THERAPEUTICS, NEURAL_CHIPS, MOOD_REGULATORS, VIRAL_AGENTS, MICRO_FUSION_GENERATORS, SUPERGRAINS, LASER_RIFLES, HOLOGRAPHICS, SHIP_SALVAGE, RELIC_TECH, NOVEL_LIFEFORMS, BOTANICAL_SPECIMENS, CULTURAL_ARTIFACTS, FRAME_PROBE, FRAME_DRONE, FRAME_INTERCEPTOR, FRAME_RACER, FRAME_FIGHTER, FRAME_FRIGATE, FRAME_SHUTTLE, FRAME_EXPLORER, FRAME_MINER, FRAME_LIGHT_FREIGHTER, FRAME_HEAVY_FREIGHTER, FRAME_TRANSPORT, FRAME_DESTROYER, FRAME_CRUISER, FRAME_CARRIER, REACTOR_SOLAR_I, REACTOR_FUSION_I, REACTOR_FISSION_I, REACTOR_CHEMICAL_I, REACTOR_ANTIMATTER_I, ENGINE_IMPULSE_DRIVE_I, ENGINE_ION_DRIVE_I, ENGINE_ION_DRIVE_II, ENGINE_HYPER_DRIVE_I, MODULE_MINERAL_PROCESSOR_I, MODULE_GAS_PROCESSOR_I, MODULE_CARGO_HOLD_I, MODULE_CARGO_HOLD_II, MODULE_CARGO_HOLD_III, MODULE_CREW_QUARTERS_I, MODULE_ENVOY_QUARTERS_I, MODULE_PASSENGER_CABIN_I, MODULE_MICRO_REFINERY_I, MODULE_SCIENCE_LAB_I, MODULE_JUMP_DRIVE_I, MODULE_JUMP_DRIVE_II, MODULE_JUMP_DRIVE_III, MODULE_WARP_DRIVE_I, MODULE_WARP_DRIVE_II, MODULE_WARP_DRIVE_III, MODULE_SHIELD_GENERATOR_I, MODULE_SHIELD_GENERATOR_II, MODULE_ORE_REFINERY_I, MODULE_FUEL_REFINERY_I, MOUNT_GAS_SIPHON_I, MOUNT_GAS_SIPHON_II, MOUNT_GAS_SIPHON_III, MOUNT_SURVEYOR_I, MOUNT_SURVEYOR_II, MOUNT_SURVEYOR_III, MOUNT_SENSOR_ARRAY_I, MOUNT_SENSOR_ARRAY_II, MOUNT_SENSOR_ARRAY_III, MOUNT_MINING_LASER_I, MOUNT_MINING_LASER_II, MOUNT_MINING_LASER_III, MOUNT_LASER_CANNON_I, MOUNT_MISSILE_LAUNCHER_I, MOUNT_TURRET_I, SHIP_PROBE, SHIP_MINING_DRONE, SHIP_SIPHON_DRONE, SHIP_INTERCEPTOR, SHIP_LIGHT_HAULER, SHIP_COMMAND_FRIGATE, SHIP_EXPLORER, SHIP_HEAVY_FREIGHTER, SHIP_LIGHT_SHUTTLE, SHIP_ORE_HOUND, SHIP_REFINING_FREIGHTER, SHIP_SURVEYOR].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TradeSymbol.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TradeSymbol"
    end
  end
end
