require 'date'
require 'time'

module SpaceRubyTraderClient
  class WaypointTraitSymbol
    UNCHARTED = "UNCHARTED".freeze
    UNDER_CONSTRUCTION = "UNDER_CONSTRUCTION".freeze
    MARKETPLACE = "MARKETPLACE".freeze
    SHIPYARD = "SHIPYARD".freeze
    OUTPOST = "OUTPOST".freeze
    SCATTERED_SETTLEMENTS = "SCATTERED_SETTLEMENTS".freeze
    SPRAWLING_CITIES = "SPRAWLING_CITIES".freeze
    MEGA_STRUCTURES = "MEGA_STRUCTURES".freeze
    PIRATE_BASE = "PIRATE_BASE".freeze
    OVERCROWDED = "OVERCROWDED".freeze
    HIGH_TECH = "HIGH_TECH".freeze
    CORRUPT = "CORRUPT".freeze
    BUREAUCRATIC = "BUREAUCRATIC".freeze
    TRADING_HUB = "TRADING_HUB".freeze
    INDUSTRIAL = "INDUSTRIAL".freeze
    BLACK_MARKET = "BLACK_MARKET".freeze
    RESEARCH_FACILITY = "RESEARCH_FACILITY".freeze
    MILITARY_BASE = "MILITARY_BASE".freeze
    SURVEILLANCE_OUTPOST = "SURVEILLANCE_OUTPOST".freeze
    EXPLORATION_OUTPOST = "EXPLORATION_OUTPOST".freeze
    MINERAL_DEPOSITS = "MINERAL_DEPOSITS".freeze
    COMMON_METAL_DEPOSITS = "COMMON_METAL_DEPOSITS".freeze
    PRECIOUS_METAL_DEPOSITS = "PRECIOUS_METAL_DEPOSITS".freeze
    RARE_METAL_DEPOSITS = "RARE_METAL_DEPOSITS".freeze
    METHANE_POOLS = "METHANE_POOLS".freeze
    ICE_CRYSTALS = "ICE_CRYSTALS".freeze
    EXPLOSIVE_GASES = "EXPLOSIVE_GASES".freeze
    STRONG_MAGNETOSPHERE = "STRONG_MAGNETOSPHERE".freeze
    VIBRANT_AURORAS = "VIBRANT_AURORAS".freeze
    SALT_FLATS = "SALT_FLATS".freeze
    CANYONS = "CANYONS".freeze
    PERPETUAL_DAYLIGHT = "PERPETUAL_DAYLIGHT".freeze
    PERPETUAL_OVERCAST = "PERPETUAL_OVERCAST".freeze
    DRY_SEABEDS = "DRY_SEABEDS".freeze
    MAGMA_SEAS = "MAGMA_SEAS".freeze
    SUPERVOLCANOES = "SUPERVOLCANOES".freeze
    ASH_CLOUDS = "ASH_CLOUDS".freeze
    VAST_RUINS = "VAST_RUINS".freeze
    MUTATED_FLORA = "MUTATED_FLORA".freeze
    TERRAFORMED = "TERRAFORMED".freeze
    EXTREME_TEMPERATURES = "EXTREME_TEMPERATURES".freeze
    EXTREME_PRESSURE = "EXTREME_PRESSURE".freeze
    DIVERSE_LIFE = "DIVERSE_LIFE".freeze
    SCARCE_LIFE = "SCARCE_LIFE".freeze
    FOSSILS = "FOSSILS".freeze
    WEAK_GRAVITY = "WEAK_GRAVITY".freeze
    STRONG_GRAVITY = "STRONG_GRAVITY".freeze
    CRUSHING_GRAVITY = "CRUSHING_GRAVITY".freeze
    TOXIC_ATMOSPHERE = "TOXIC_ATMOSPHERE".freeze
    CORROSIVE_ATMOSPHERE = "CORROSIVE_ATMOSPHERE".freeze
    BREATHABLE_ATMOSPHERE = "BREATHABLE_ATMOSPHERE".freeze
    THIN_ATMOSPHERE = "THIN_ATMOSPHERE".freeze
    JOVIAN = "JOVIAN".freeze
    ROCKY = "ROCKY".freeze
    VOLCANIC = "VOLCANIC".freeze
    FROZEN = "FROZEN".freeze
    SWAMP = "SWAMP".freeze
    BARREN = "BARREN".freeze
    TEMPERATE = "TEMPERATE".freeze
    JUNGLE = "JUNGLE".freeze
    OCEAN = "OCEAN".freeze
    RADIOACTIVE = "RADIOACTIVE".freeze
    MICRO_GRAVITY_ANOMALIES = "MICRO_GRAVITY_ANOMALIES".freeze
    DEBRIS_CLUSTER = "DEBRIS_CLUSTER".freeze
    DEEP_CRATERS = "DEEP_CRATERS".freeze
    SHALLOW_CRATERS = "SHALLOW_CRATERS".freeze
    UNSTABLE_COMPOSITION = "UNSTABLE_COMPOSITION".freeze
    HOLLOWED_INTERIOR = "HOLLOWED_INTERIOR".freeze
    STRIPPED = "STRIPPED".freeze

    def self.all_vars
      @all_vars ||= [UNCHARTED, UNDER_CONSTRUCTION, MARKETPLACE, SHIPYARD, OUTPOST, SCATTERED_SETTLEMENTS, SPRAWLING_CITIES, MEGA_STRUCTURES, PIRATE_BASE, OVERCROWDED, HIGH_TECH, CORRUPT, BUREAUCRATIC, TRADING_HUB, INDUSTRIAL, BLACK_MARKET, RESEARCH_FACILITY, MILITARY_BASE, SURVEILLANCE_OUTPOST, EXPLORATION_OUTPOST, MINERAL_DEPOSITS, COMMON_METAL_DEPOSITS, PRECIOUS_METAL_DEPOSITS, RARE_METAL_DEPOSITS, METHANE_POOLS, ICE_CRYSTALS, EXPLOSIVE_GASES, STRONG_MAGNETOSPHERE, VIBRANT_AURORAS, SALT_FLATS, CANYONS, PERPETUAL_DAYLIGHT, PERPETUAL_OVERCAST, DRY_SEABEDS, MAGMA_SEAS, SUPERVOLCANOES, ASH_CLOUDS, VAST_RUINS, MUTATED_FLORA, TERRAFORMED, EXTREME_TEMPERATURES, EXTREME_PRESSURE, DIVERSE_LIFE, SCARCE_LIFE, FOSSILS, WEAK_GRAVITY, STRONG_GRAVITY, CRUSHING_GRAVITY, TOXIC_ATMOSPHERE, CORROSIVE_ATMOSPHERE, BREATHABLE_ATMOSPHERE, THIN_ATMOSPHERE, JOVIAN, ROCKY, VOLCANIC, FROZEN, SWAMP, BARREN, TEMPERATE, JUNGLE, OCEAN, RADIOACTIVE, MICRO_GRAVITY_ANOMALIES, DEBRIS_CLUSTER, DEEP_CRATERS, SHALLOW_CRATERS, UNSTABLE_COMPOSITION, HOLLOWED_INTERIOR, STRIPPED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WaypointTraitSymbol.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WaypointTraitSymbol"
    end
  end
end
